lzc-sdk-version: "0.1"
name: Domain Admin
package: cloud.lzaycat.app.domain-admin
version: 1.6.65
description: 域名和SSL证书监测平台
homepage: https://github.com/dromara/domain-admin
author: dromara
application:
  subdomain: domain-admin
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://domain-admin.cloud.lzaycat.app.domain-admin.lzcapp:8000/
services:
  domain-admin:
    image: docker.hlmirror.com/mouday/domain-admin:latest
    binds:
      - /lzcapp/var/database:/app/database
      - /lzcapp/var/logs:/app/logs
unsupported_platforms:
  - ios
  - android
  - tvos
